"use client";

import { useState } from "react";
import Link from "next/link";
import {
  BarChart3,
  GitBranch,
  FileText,
  Target,
  Globe,
  Compass,
  CheckCircle,
  ArrowUpRight,
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

const PREVIEW_TABS = [
  { id: "score", name: "Developer Score", icon: BarChart3, color: "text-blue-400" },
  { id: "github", name: "GitHub Analysis", icon: GitBranch, color: "text-cyan-400" },
  { id: "resume", name: "Resume Analysis", icon: FileText, color: "text-purple-400" },
  { id: "skills", name: "Skill Gap Analysis", icon: Target, color: "text-pink-400" },
  { id: "portfolio", name: "Portfolio Score", icon: Globe, color: "text-emerald-400" },
  { id: "readiness", name: "Career Readiness", icon: Compass, color: "text-violet-400" },
];

export function ProductPreview() {
  const [activeTab, setActiveTab] = useState("score");

  return (
    <section id="preview" className="relative py-28 border-t border-white/5 bg-zinc-950">
      {/* Background radial blurs */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[400px] bg-cyan-500/5 rounded-full blur-[140px] pointer-events-none" />
      <div className="absolute top-1/3 left-1/4 w-[500px] h-[300px] bg-purple-500/5 rounded-full blur-[120px] pointer-events-none" />

      <div className="relative mx-auto max-w-6xl px-6">
        
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="text-center max-w-2xl mx-auto"
        >
          <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-cyan-950/20 border border-cyan-800/30 px-3.5 py-1 text-[10px] font-bold text-cyan-400 uppercase tracking-widest">
            Live Showcase
          </div>
          <h2 className="text-3xl font-black tracking-tight sm:text-4xl text-white">
            Explore the AI Workspace
          </h2>
          <p className="mt-4 text-sm sm:text-base text-zinc-400 leading-relaxed font-medium">
            Get telemetry-driven insights inside a unified dashboard. Explore the interactive modules below to see the depth of analysis generated by DevLeveler.
          </p>
        </motion.div>

        {/* Dashboard Preview Shell */}
        <div className="mt-16 grid gap-8 lg:grid-cols-12 items-start">
          
          {/* Left Tabs Menu */}
          <div className="lg:col-span-4 flex flex-row lg:flex-col overflow-x-auto lg:overflow-x-visible gap-1.5 bg-zinc-900/30 p-2 rounded-2xl border border-white/5 hide-scrollbar shrink-0">
            {PREVIEW_TABS.map((tab) => {
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-3.5 px-4.5 py-3.5 rounded-xl text-left text-xs font-bold whitespace-nowrap transition-all duration-300 flex-1 lg:flex-none relative ${
                    isActive 
                      ? "text-white" 
                      : "text-zinc-500 hover:text-zinc-300"
                  }`}
                >
                  {isActive && (
                    <motion.div
                      layoutId="preview-active-pill"
                      className="absolute inset-0 bg-white/5 border border-white/10 rounded-xl shadow-lg"
                      transition={{ type: "spring", stiffness: 350, damping: 25 }}
                    />
                  )}
                  <tab.icon className={`h-4.5 w-4.5 shrink-0 relative z-10 transition-colors duration-300 ${isActive ? tab.color : "text-zinc-500"}`} />
                  <span className="relative z-10">{tab.name}</span>
                </button>
              );
            })}
          </div>

          {/* Right Preview Card Workspace */}
          <div className="lg:col-span-8 bg-zinc-900/40 border border-white/10 rounded-2xl p-6 shadow-2xl relative min-h-[380px] flex flex-col justify-between overflow-hidden backdrop-blur-md">
            
            {/* Window Header */}
            <div className="flex items-center justify-between pb-4 border-b border-white/5 mb-6">
              <div className="flex items-center gap-1.5">
                <div className="w-2.5 h-2.5 rounded-full bg-red-500/40" />
                <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/40" />
                <div className="w-2.5 h-2.5 rounded-full bg-green-500/40" />
                <span className="text-[10px] font-mono text-zinc-500 ml-2">devleveler.com/workspace/{activeTab}</span>
              </div>
              <span className="text-[9px] text-zinc-600 font-extrabold uppercase tracking-widest font-mono">Module Preview</span>
            </div>

            {/* Content Previews */}
            <div className="flex-1 flex flex-col justify-center">
              <AnimatePresence mode="wait">
                
                {/* 1. Developer Score */}
                {activeTab === "score" && (
                  <motion.div
                    key="score"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="grid gap-6 md:grid-cols-12 items-center"
                  >
                    <div className="md:col-span-5 flex flex-col items-center justify-center rounded-2xl border border-white/5 bg-zinc-950/45 p-6 shadow-inner">
                      <span className="text-[9px] font-extrabold text-zinc-500 uppercase tracking-widest">AI Readiness Score</span>
                      <div className="relative flex items-center justify-center w-32 h-32 mt-5">
                        <svg width="120" height="120" viewBox="0 0 100 100">
                          <circle cx="50" cy="50" r="42" fill="none" stroke="rgba(255,255,255,0.03)" strokeWidth="6" />
                          <circle cx="50" cy="50" r="42" fill="none" stroke="url(#demoScoreGradient)" strokeWidth="6" strokeDasharray="263.8" strokeDashoffset="42" transform="rotate(-90 50 50)" strokeLinecap="round" />
                          <defs>
                            <linearGradient id="demoScoreGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                              <stop offset="0%" stopColor="#00f0ff" />
                              <stop offset="100%" stopColor="#a855f7" />
                            </linearGradient>
                          </defs>
                        </svg>
                        <span className="absolute text-3.5xl font-black text-white tracking-tighter">84</span>
                      </div>
                      <span className="text-[10px] text-emerald-400 font-bold mt-4">Level 4: Professional Builder</span>
                    </div>
                    
                    <div className="md:col-span-7 space-y-4">
                      <div>
                        <h4 className="text-sm font-extrabold text-white mb-1.5">Telemetry Weights Breakdown</h4>
                        <p className="text-xs text-zinc-400 leading-relaxed">
                          Your overall score weights core telemetry inputs across commits, clean code architecture, and deployment tests.
                        </p>
                      </div>
                      <div className="space-y-3.5">
                        {[
                          { name: "Repository Code Quality", wt: "30%", score: 86, color: "from-blue-500 to-cyan-400" },
                          { name: "GitHub Activity Footprint", wt: "25%", score: 92, color: "from-cyan-400 to-cyan-600" },
                          { name: "Skills Balance Matrix", wt: "20%", score: 75, color: "from-indigo-500 to-purple-500" },
                          { name: "ATS Resume Match Rate", wt: "15%", score: 80, color: "from-emerald-400 to-teal-500" },
                        ].map((m) => (
                          <div key={m.name} className="text-xs">
                            <div className="flex justify-between text-[11px] mb-1.5 font-semibold">
                              <span className="text-zinc-400">{m.name} ({m.wt})</span>
                              <span className="text-white font-extrabold">{m.score}/100</span>
                            </div>
                            <div className="h-1.5 w-full bg-white/5 rounded-full overflow-hidden">
                              <div className={`h-full bg-gradient-to-r ${m.color} rounded-full`} style={{ width: `${m.score}%` }} />
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </motion.div>
                )}

                {/* 2. GitHub Analysis */}
                {activeTab === "github" && (
                  <motion.div
                    key="github"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="space-y-6"
                  >
                    <div className="grid gap-4 sm:grid-cols-3">
                      {[
                        { label: "Active Repositories", val: "48", desc: "Production Synced" },
                        { label: "Community Stars", val: "1.2K", desc: "Total Stars Earned" },
                        { label: "Recent Commits", val: "342", desc: "Past 90 Days" },
                      ].map((item) => (
                        <div key={item.label} className="rounded-2xl border border-white/5 bg-zinc-950/45 p-4.5 text-center hover:border-cyan-500/10 transition-colors">
                          <span className="text-[9px] font-extrabold text-zinc-500 uppercase tracking-wider">{item.label}</span>
                          <span className="text-2.5xl font-black text-white block mt-1.5 tracking-tight">{item.val}</span>
                          <span className="text-[10px] text-zinc-400 block mt-1 font-medium">{item.desc}</span>
                        </div>
                      ))}
                    </div>

                    {/* Language charts mock */}
                    <div className="rounded-2xl border border-white/5 bg-zinc-950/45 p-5 flex items-center justify-between">
                      <div className="space-y-3.5 w-1/2">
                        <span className="text-[9px] font-extrabold text-zinc-500 uppercase tracking-widest block">Language Balance</span>
                        <div className="space-y-2">
                          {[
                            { name: "TypeScript", pct: "64%", color: "bg-blue-500" },
                            { name: "Python", pct: "22%", color: "bg-amber-400" },
                            { name: "Rust", pct: "14%", color: "bg-orange-500" },
                          ].map((l) => (
                            <div key={l.name} className="flex items-center gap-2 text-xs">
                              <span className={`h-2.5 w-2.5 rounded-full ${l.color}`} />
                              <span className="text-zinc-400 font-semibold">{l.name}</span>
                              <span className="text-white font-extrabold ml-auto">{l.pct}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                      <div className="flex flex-col items-end gap-2.5 w-1/2">
                        <span className="text-[9px] font-mono text-zinc-500 uppercase font-extrabold">Commit Velocity Map</span>
                        <svg viewBox="0 0 100 30" className="w-full max-w-[160px] h-12 stroke-cyan-400 fill-none">
                          <path d="M0,25 Q15,10 30,20 T60,5 T90,15 L100,5" strokeWidth="2.5" strokeLinecap="round" />
                        </svg>
                      </div>
                    </div>
                  </motion.div>
                )}

                {/* 3. Resume Analysis */}
                {activeTab === "resume" && (
                  <motion.div
                    key="resume"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="grid gap-6 md:grid-cols-2"
                  >
                    <div className="rounded-2xl border border-white/5 bg-zinc-950/45 p-5 flex flex-col justify-between">
                      <div>
                        <span className="text-[9px] font-extrabold text-zinc-500 uppercase tracking-widest">ATS Audit Rating</span>
                        <div className="flex items-baseline gap-1.5 mt-3">
                          <span className="text-4xl font-black text-emerald-400">89</span>
                          <span className="text-xs text-zinc-500 font-bold">/100</span>
                        </div>
                        <p className="text-xs text-zinc-400 leading-relaxed mt-4 font-medium">
                          Your resume structure, header format, and bullet achievements are highly optimized for technical scanners.
                        </p>
                      </div>
                      <div className="mt-4 pt-3.5 border-t border-white/5 text-[10px] text-emerald-400 font-bold flex items-center gap-2">
                        <CheckCircle className="h-4 w-4" />
                        Zero layout errors detected
                      </div>
                    </div>

                    <div className="rounded-2xl border border-white/5 bg-zinc-950/45 p-5 space-y-4">
                      <div>
                        <span className="text-[9px] font-extrabold text-amber-500 uppercase tracking-widest block mb-2">High Impact Keyword Gaps</span>
                        <p className="text-xs text-zinc-400 font-medium">
                          Adding these keywords to your project descriptions can improve search relevance:
                        </p>
                      </div>
                      <div className="space-y-2">
                        {[
                          { word: "Kubernetes Orchestration", impact: "High Impact" },
                          { word: "GraphQL Resolvers", impact: "Medium Impact" },
                          { word: "CI/CD Pipeline Build", impact: "High Impact" },
                        ].map((w) => (
                          <div key={w.word} className="flex justify-between items-center text-xs p-2 bg-zinc-950/80 rounded-xl border border-white/5">
                            <span className="font-mono text-zinc-300 font-bold">{w.word}</span>
                            <span className="text-[8px] uppercase font-extrabold text-amber-500 bg-amber-500/10 px-2 py-0.5 rounded-full border border-amber-500/20">{w.impact}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </motion.div>
                )}

                {/* 4. Skill Gaps */}
                {activeTab === "skills" && (
                  <motion.div
                    key="skills"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="space-y-4"
                  >
                    <div className="rounded-2xl border border-white/5 bg-zinc-950/45 p-4.5 flex items-center justify-between text-xs">
                      <div>
                        <span className="text-[9px] font-extrabold text-zinc-500 tracking-widest uppercase block">Market Balance Matrix</span>
                        <span className="text-sm font-bold text-white mt-1 block">Full-stack Balance: 74%</span>
                      </div>
                      <span className="text-[10px] font-bold text-pink-400 bg-pink-950/20 border border-pink-900/30 px-2.5 py-1 rounded-full">Target: Fullstack</span>
                    </div>

                    <div className="space-y-2.5">
                      {[
                        { skill: "Docker & Containerization", priority: "critical", action: "Dockerize local app, write compose scripts" },
                        { skill: "Redis Caching Layer", priority: "important", action: "Integrate Redis caching to backend user profile APIs" },
                        { skill: "AWS S3 / Cloud Bucket Deploy", priority: "optional", action: "Deploy asset pipeline to cloud bucket storage" },
                      ].map((item) => (
                        <div key={item.skill} className="rounded-2xl border border-white/5 bg-zinc-950/45 p-3.5 flex items-center justify-between gap-4 text-xs">
                          <div>
                            <span className="font-bold text-white block">{item.skill}</span>
                            <span className="text-[10px] text-zinc-500 mt-1 block">{item.action}</span>
                          </div>
                          <span className={`text-[8px] font-extrabold uppercase tracking-widest px-2.5 py-1 rounded-full border ${
                            item.priority === "critical" ? "bg-red-950/20 text-red-400 border-red-900/30" :
                            item.priority === "important" ? "bg-amber-950/20 text-amber-400 border-amber-900/30" :
                            "bg-zinc-900 text-zinc-400 border-zinc-800"
                          }`}>
                            {item.priority}
                          </span>
                        </div>
                      ))}
                    </div>
                  </motion.div>
                )}

                {/* 5. Portfolio Score */}
                {activeTab === "portfolio" && (
                  <motion.div
                    key="portfolio"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="grid gap-4 md:grid-cols-3"
                  >
                    {[
                      { title: "Lighthouse Performance", grade: "96%", desc: "PageSpeed & Asset load speeds", color: "text-emerald-400" },
                      { title: "Design & UX Consistency", grade: "82%", desc: "Responsive layout structure", color: "text-blue-400" },
                      { title: "Semantic Code Audit", grade: "90%", desc: "HTML5 tags & clean DOM size", color: "text-cyan-400" },
                    ].map((card) => (
                      <div key={card.title} className="rounded-2xl border border-white/5 bg-zinc-950/45 p-5 text-center flex flex-col justify-between min-h-[150px] hover:border-emerald-500/10 transition-all duration-300">
                        <div>
                          <span className="text-[9px] font-extrabold text-zinc-500 uppercase tracking-widest block">{card.title}</span>
                          <span className={`text-3xl font-black ${card.color} block mt-3.5 tracking-tight`}>{card.grade}</span>
                        </div>
                        <span className="text-[10px] text-zinc-400 leading-relaxed mt-3.5 block font-medium">{card.desc}</span>
                      </div>
                    ))}
                  </motion.div>
                )}

                {/* 6. Career Readiness */}
                {activeTab === "readiness" && (
                  <motion.div
                    key="readiness"
                    initial={{ opacity: 0, x: 12, filter: "blur(4px)" }}
                    animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                    exit={{ opacity: 0, x: -12, filter: "blur(4px)" }}
                    transition={{ duration: 0.3 }}
                    className="space-y-4"
                  >
                    <div className="grid gap-4 sm:grid-cols-2">
                      <div className="rounded-2xl border border-white/5 bg-zinc-950/45 p-4.5">
                        <span className="text-[9px] font-extrabold text-zinc-500 uppercase tracking-widest block mb-2">Startup Fit</span>
                        <div className="flex items-baseline gap-1.5">
                          <span className="text-3xl font-black text-cyan-400">92%</span>
                          <span className="text-[9px] font-bold text-emerald-400 bg-emerald-950/20 border border-emerald-900/30 px-2 py-0.5 rounded-full">Highly Ready</span>
                        </div>
                        <p className="text-[10px] text-zinc-400 leading-relaxed mt-2.5 font-medium">
                          Excellent ship velocity, diverse stack, and high repository creation frequencies align with startup environments.
                        </p>
                      </div>

                      <div className="rounded-2xl border border-white/5 bg-zinc-950/45 p-4.5">
                        <span className="text-[9px] font-extrabold text-zinc-500 uppercase tracking-widest block mb-2">Enterprise Fit</span>
                        <div className="flex items-baseline gap-1.5">
                          <span className="text-3xl font-black text-violet-400">76%</span>
                          <span className="text-[9px] font-bold text-zinc-400 bg-zinc-900 border border-zinc-800 px-2 py-0.5 rounded-full">Moderately Ready</span>
                        </div>
                        <p className="text-[10px] text-zinc-400 leading-relaxed mt-2.5 font-medium">
                          Requires adding systematic unit/integration testing portfolios and architecture documentation trees.
                        </p>
                      </div>
                    </div>

                    <div className="rounded-2xl border border-white/5 bg-zinc-950/45 p-4.5 flex items-center justify-between text-xs">
                      <div className="flex items-center gap-2.5">
                        <Compass className="h-4.5 w-4.5 text-violet-400" />
                        <span className="text-zinc-400 font-semibold">Career Track Focus:</span>
                        <span className="font-bold text-white">Fullstack (Web)</span>
                      </div>
                      <span className="text-[10px] font-bold text-emerald-400">Rank: Explorer II</span>
                    </div>
                  </motion.div>
                )}

              </AnimatePresence>
            </div>

            {/* Bottom CTA bar */}
            <div className="mt-6 pt-4 border-t border-white/5 flex items-center justify-between text-xs text-zinc-400 font-medium">
              <span>Ready to check your actual scores?</span>
              <Link 
                href="/login"
                className="inline-flex items-center gap-1.5 font-bold text-cyan-400 hover:text-cyan-300"
              >
                Scan Profile Now
                <ArrowUpRight className="h-4 w-4" />
              </Link>
            </div>

          </div>

        </div>
      </div>
    </section>
  );
}
